### ISSUE TITLE
No slack attribute when unit set to outage with 0 max capacity and 0 volume bids

### ISSUE THREAD

**Issue by dehorsley** [UNSW-CEEM/nempy#14] opened 2023-01-12 06:14 UTC
Hi there,

First of all, thanks for all your work on this package and excellent documentation!

I've encounter a small issue with some inputs I was trying. After some work, I found the issue was partly due to some iffy inputs of mine (stemming from an upstream model), but the error message I was getting wasn't particularly illuminating, so maybe something can be done to save someone else some debugging time.

Specifically, the inputs I used have a unit on outage. This is set by having the volume bids all set to 0, and the maximum capacity set to 0. With this, I get an exception thrown when `nempy` tries to read the slack of the constraint. I'm guessing the solver has dropped the constraint altogether as it is solved identically. 

Below is a minimal example. Tried in nempy version 1.1.5, python-mip 1.15.0.

```python
import pandas as pd
from nempy import markets

# Unit 'C' is on outage, energy bids all 0

volume_bids = pd.DataFrame({
    'unit': ['A', 'B', 'C'],
    '1': [20.0, 50.0, 0.0],
    '2': [20.0, 30.0, 0.0],
    '3': [5.0, 10.0, 0.0]
})

price_bids = pd.DataFrame({
    'unit': ['A', 'B', 'C'],
    '1': [50.0, 50.0, 0.0],
    '2': [60.0, 55.0, 0.0], 
    '3': [100.0, 80.0, 0.0]
})

unit_info = pd.DataFrame({
    'unit': ['A', 'B', 'C'],
    'region': ['NSW', 'NSW', 'NSW'],
})

# Max capacity also set to 0 for unit 'C'
max_capacity = pd.DataFrame({
    'unit': ['A', 'B', 'C'],
    'capacity': [50.0, 100.0, 0.0],
})

demand = pd.DataFrame({
    'region': ['NSW'],
    'demand': [120.0]
})

market = markets.SpotMarket(unit_info=unit_info, 
                            market_regions=['NSW'])
market.set_unit_volume_bids(volume_bids)
market.set_unit_price_bids(price_bids)
market.set_demand_constraints(demand)
market.set_unit_bid_capacity_constraints(max_capacity)

market.dispatch() 

```
The `dispatch` call raises `AttributeError: 'NoneType' object has no attribute 'slack' `
in  [`InterfaceToSolver.get_slack_in_constraints`](https://github.com/UNSW-CEEM/nempy/blob/73609a0552eff1a0dc500f9d5b9d94f40eca0f9c/nempy/spot_markert_backend/solver_interface.py#L389)

I think as a fix, at a minimum a more useful error message could be set here, but a more comprehensive change would be to have a default `slack` for eliminated constraints eg change

```
slack = constraints_type_and_rhs['constraint_id'].apply(lambda x: self.mip_model.constr_by_name(str(x)).slack,
                                                                self.mip_model)
```

to 

```python
slack = constraints_type_and_rhs['constraint_id'].apply(
    lambda x: getattr(self.mip_model.constr_by_name(str(x)), "slack", 0.0),
    self.mip_model
)
```

(Unrelated, but I think that second argument to `.apply` is unused)

This might have broader consequences though and maybe `0.0` isn't the correct default.

Cheers.

**Comment by dehorsley** [comment] 2023-01-12 22:46
Actually I realise it's not the solver that dropped the constraint, it's that nempy doesn't create decision variables for 0 capacity bids, so the capacity constraint contains no variables.

**Comment by nick-gorman** [comment] 2023-01-13 01:17
Hi @dehorsley,

Thanks for raising this issue, really appreciate the feedback. Also, thanks for including an example to reproduce the error.

I think there are three options to fix this,

1) When set_unit_bid_capacity_constraints is run, check that there are decision variables for each unit and if some are missing explicitly throw an error that says this.
2) When set_unit_bid_capacity_constraints is run, don't set constraints for units without decision variables and warn the user.
3) When set_unit_bid_capacity_constraints is run, silently don't set constraints for units without decision variables.

Any thoughts as user about which one sounds most reasonable to you?

**Comment by dehorsley** [comment] 2023-01-13 01:48
Hi @nick-gorman,

Thanks for the quick response. I think option 3 would be my preferred solution. My thinking is that not adding decision variables for 0 capacity bids is kind of an optimisation nempy is doing, so not something a user needs to worry about.

On the other hand, perhaps option 2 would catch some user errors on input, but at least in my case 😄 not something I'd need.

**Comment by nick-gorman** [comment] 2023-01-13 02:59
After a bit more investigating, I think this bug could be replicated across most if not all constraint types, i.e. other cases where the user specifies constraint but they never get created because there are no LHS variables.

From a functionality and performance perspective, this is fine. Even preferable from a performance perspective.

But solving the no slack problem using my above suggestions will be difficult to replicate across all instances of the bug.

So I think your original suggestion to have a default value might be the best solution to patch the bug across all constraint types.

I think a default of zero makes sense for constraints with no LHS variables, although this behaviour should be documented so users don't get confused.

**Comment by nick-gorman** [comment] 2023-01-13 04:22
Fixed with release: https://github.com/UNSW-CEEM/nempy/releases/tag/v1.1.6

**Closed by nick-gorman** 2023-01-13 04:22 UTC
